#!/bin/sh -e

# Source debconf library.
. /usr/share/debconf/confmodule

db_input high _APP_NAME_/welcome || true
db_go

# Do you like debian?
db_input high _APP_NAME_/like_debian || true
db_go

# Check their answer.
db_get _APP_NAME_/like_debian
if [ "$RET" = "false" ]; then
  # Poor misguided one..
  db_input high _APP_NAME_/why_debian_is_great || true
  db_go
fi
